SEQUENCE_LENGTH = 12
HIDDEN_SIZE = 32
NUM_EPOCHS = 50
BATCH_SIZE = 32
LEARNING_RATE = 0.001

TRAIN_SPLIT = 0.70
VAL_SPLIT = 0.15
TEST_SPLIT = 0.15

DATA_FILE = 'traffic_data.csv'
MODEL_DIR = 'model'

TIME_FEATURES = 8

RUSH_HOUR_MORNING = (7, 9)
RUSH_HOUR_EVENING = (16, 19)
NIGHT_TIME = (22, 4)

STEP_INTERVAL_MS = 5000
STRIDE_INTERVAL_MS = 15000
WINDOW_SIZE_MS = 60000

POINTS_PER_WINDOW = WINDOW_SIZE_MS // STEP_INTERVAL_MS
POINTS_PER_STRIDE = STRIDE_INTERVAL_MS // STEP_INTERVAL_MS